### PR TITLE
Allow requests with underscore to api2cart

### PR DESCRIPTION
**Pull request by aziret**

### CODE REVIEW

**Comment by DanielVartanov** [comment]
Please add a correspondent test.

**Comment by aziret** [comment]
Hey, @DanielVartanov !

**Comment by DanielVartanov** [comment]
Well, I just see you have changed _behaviour_ of URL composition, which obviously means a test should be added/edited even if it was a quick solution. Is there any reason why shouldn't we do it in this case?

**Comment by aziret** [comment]
I'm working on moving to api2cart API V1.1 on Veeqo side. In API V1.0 product info contains information about its variants as well, but API V1.1 doesn't. So to get them one needs to make another request to either `product.variant.list` or `product.child_item.list`. But `product.variant.list` doesn't contain some fields we needed, as far as I remember (I'll check it), that's why I use `product.child_item.list` endpoint.

**Comment by DanielVartanov** [comment]
@aziret sorry for being dumb, but I do not understand how is it related to the absence of tests? Can you please explain?

**Comment by DanielVartanov** [comment]
Great, thanks for adding them :+1:

**Pull request merged**
